# Generated by Django 5.2.8 on 2025-11-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BatteryStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prediction", models.IntegerField()),
                (
                    "status_title",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical"),
                            ("Warning", "Warning"),
                            ("Normal", "Normal"),
                            ("Full", "Full"),
                            ("Charging", "Charging"),
                        ]
                    ),
                ),
                ("node_address", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="StatusSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status_title",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical"),
                            ("Warning", "Warning"),
                            ("Normal", "Normal"),
                            ("Full", "Full"),
                            ("Charging", "Charging"),
                        ]
                    ),
                ),
                ("count", models.IntegerField()),
            ],
        ),
    ]
