# Generated by Django 6.0 on 2025-12-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battery_status", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batterystatus",
            name="node_address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="batterystatus",
            name="status_title",
            field=models.CharField(
                choices=[("Normal", "Normal"), ("Low", "Low"), ("Offline", "Offline")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="statussummary",
            name="status_title",
            field=models.CharField(
                choices=[("Normal", "Normal"), ("Low", "Low"), ("Offline", "Offline")],
                max_length=20,
            ),
        ),
    ]
