# Generated by Django 6.0.1 on 2026-01-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("battery_status", "0004_batterystatus_prediction_days_and_more"),
    ]

    operations = []
