# Generated by Django 6.0.1 on 2026-01-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("battery_status", "0005_auto_20260110_1652"),
    ]

    operations = [
        migrations.RenameField(
            model_name="batterystatus",
            old_name="battery_percentage",
            new_name="percentage",
        ),
        migrations.RenameField(
            model_name="batterystatus",
            old_name="status_title",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="statussummary",
            old_name="status_title",
            new_name="title",
        ),
    ]
