# Generated by Django 6.0.1 on 2026-01-13 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "battery_status",
            "0006_rename_battery_percentage_batterystatus_percentage_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("total_tags", models.IntegerField()),
                ("normal_count", models.IntegerField()),
                ("low_count", models.IntegerField()),
                ("offline_count", models.IntegerField()),
                (
                    "average_percentage",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="StatusSummary",
        ),
    ]
