# Generated by Django 6.0.1 on 2026-01-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battery_status", "0007_summary_delete_statussummary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
