# Generated by Django 6.0 on 2025-12-15 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0003_remove_type_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["node_address"]},
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="tag_id",
            new_name="node_address",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="status",
        ),
    ]
