# Generated by Django 6.0.1 on 2026-01-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0004_alter_tag_options_rename_tag_id_tag_node_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="battery_level",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="id",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="prediction",
        ),
        migrations.AddField(
            model_name="tag",
            name="online_status",
            field=models.CharField(
                blank=True,
                choices=[("online", "Online"), ("offline", "Offline")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="tag_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
