# Generated by Django 6.0.1 on 2026-01-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0005_remove_tag_battery_level_remove_tag_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="tag_id",
        ),
        migrations.AddField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
